services:
  app:
    build:
      context: ./web
      dockerfile: ../dockerfile/Dockerfile.web
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./web:/app
    stdin_open: true
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - ./web/.env
